version: "3.7"
services:
        validator-import-launchpad:
                container_name: validator-import-launchpad
                image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_DOCKER_TAG}
                command: accounts-v2 import --keys-dir="/launchpad/eth2.0-deposit-cli/validator_keys" --wallet-dir="/data/wallets" --wallet-password-file="/data/passwords/wallet-password" --password="AbCd1@3$"
                volumes:
                        - ./validator:/data
                        - ./launchpad:/launchpad
        validator-list-accounts:
                container_name: validator_list_accounts
                image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_DOCKER_TAG}
                command: accounts-v2 list --wallet-dir="/data/wallets" --wallet-password-file="/data/passwords/wallet-password" --password="AbCd1@3$"
                volumes:
                        - ./validator:/data
